import { useState } from 'react';
import Head from 'next/head';
import styles from '@/styles/Home.module.css';

export default function Calculator() {
  const [text, setText] = useState('');
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [variables, setVariables] = useState({text: false, name: false, email: false});
  const [isValid, setIsValid] = useState(false);

  const validateInputs = () => {
    const isTextValid = text.trim().length > 0;
    const isNameValid = name.trim().length > 0;
    const isEmailValid = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);

    setIsValid(isTextValid && isNameValid && isEmailValid);
  };

  const handleValidation = () => {
    validateInputs();
    const textInput = document.getElementById('text-input');
    const nameInput = document.getElementById('name-input');
    const emailInput = document.getElementById('email-input');
    if (!isValid) {
      if (!text.trim()) {
        variables.text = true;
      }
      if (!name.trim()) {
        variables.name = true;
      }
      if (!email.trim() || !/^([a-zA-Z0-9._%-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6})*$/.test(email.trim())) {
        variables.email = true;
      }
    } else {
      textInput.className = styles.enterText;
      nameInput.className = styles.enterText;
      emailInput.className = styles.enterText;
    }

    setVariables({...variables})
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.enterText}>
          <text>Ulice</text>
          <input style={variables.text ? styles.enterText : styles.errorInput} type="text" id="text-input" value={text} onChange={(e) => setText(e.target.value)} />
        </div>
        <div className={styles.enterText}>
          <text>Jméno</text>
          <input style={variables.name ? styles.enterText : styles.errorInput} type="text" id="name-input" value={name} onChange={(e) => setName(e.target.value)} />
        </div>
        <div className={styles.enterText}>
          <text>E-mail</text>
          <input style={variables.email ? styles.enterText : styles.errorInput} type="text" id="email-input" value={email} onChange={(e) => setEmail(e.target.value)} />
        </div>
        <button onClick={handleValidation}>Validate</button>
        {!isValid && <p>Some inputs are invalid!</p>}
      </main>
    </>
  );
}